#!/bin/zsh

#ARG THEANO_VERSION=rel-0.8.2
#ARG TENSORFLOW_VERSION=0.12.1
#ARG TENSORFLOW_ARCH=gpu
#ARG KERAS_VERSION=1.2.0
#ARG LASAGNE_VERSION=v0.1
#ARG TORCH_VERSION=latest
#ARG CAFFE_VERSION=master

nvidia-docker build --pull --tag floydhub/dl-docker:gpu --file Dockerfile.gpu --build-arg TENSORFLOW_VERSION=1.1.0rc2 .
